version: '3.3'

services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4001:4001
    depends_on:
      - mongo
    links:
      - mongo
    volumes:
      - .:/usr/src/app
    environment:
      MONGO_USER: root
      MONGO_PASSWORD: example
      MONGO_HOSTNAME: mongo
      MONGO_PORT: 27017
      PORT: 4001
    command: npm run start:dev

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express-browser:
    image: mongo-express
    ports:
      - 8081:8081
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_URL: "mongodb://root:example@mongo:27017/"